# Generated by Django 5.2.7 on 2025-10-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0002_employee_address_employee_city_employee_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
    ]
