# Generated by Django 5.2.7 on 2025-10-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0003_remove_employee_address_remove_employee_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_status',
            field=models.CharField(default='Absent', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='E_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
