# Generated by Django 5.2.7 on 2025-10-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0005_remove_employee_attendance_status_employee_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
