# Generated by Django 5.2.7 on 2025-11-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0006_employee_is_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_view_attendance', 'Can view attendance records'), ('can_edit_salary', 'Can edit employee salary'), ('can_add_employee', 'Can add new employees'), ('can_delete_employee', 'Can delete employees'), ('can_view_reports', 'Can view reports')]},
        ),
    ]
