# Generated by Django 5.2.7 on 2025-11-20 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0007_alter_employee_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_view_attendance', 'Can view attendance records'), ('can_edit_salary', 'Can edit employee salary'), ('can_add_employee', 'Can add new employees'), ('can_delete_employee', 'Can delete employees'), ('can_view_reports', 'Can view reports'), ('can_manipulate_salary', 'Can manipulate calculated salary')]},
        ),
        migrations.AddField(
            model_name='attendance',
            name='adjustment_reason',
            field=models.TextField(blank=True, help_text='Reason for manual adjustment', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='auto_checkout',
            field=models.BooleanField(default=False, help_text='True if checked out automatically by system'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkout_reason',
            field=models.CharField(blank=True, help_text='Reason for checkout (manual/auto)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='manual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='HR can manually set hours if needed', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Hourly rate in ₹', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed monthly salary', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_type',
            field=models.CharField(choices=[('monthly', 'Monthly Fixed (Days-based)'), ('hourly', 'Hourly Rate (Hours-based)')], default='monthly', help_text='Select salary calculation method', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='standard_hours_per_day',
            field=models.IntegerField(default=8, help_text='Standard working hours per day'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Legacy salary field', max_digits=10),
        ),
        migrations.CreateModel(
            name='SalaryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('calculated_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjusted_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment_reason', models.TextField()),
                ('adjusted_on', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locationapp.employee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
