# Generated by Django 5.2.7 on 2025-11-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0008_alter_employee_options_attendance_adjustment_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_holiday',
            field=models.BooleanField(default=False, help_text='True if this is a holiday'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_sunday',
            field=models.BooleanField(default=False, help_text='True if this is a Sunday (overtime day)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime_rate_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Overtime rate multiplier (1.5 = 150% of hourly rate)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='adjustment_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='auto_checkout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checkout_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='manual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed monthly salary (for 26 working days)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='standard_hours_per_day',
            field=models.IntegerField(default=8, help_text='Standard working hours per day (8 hours = 1 full day)'),
        ),
    ]
